[[redirects]]
from = "/assets/backgrounds/*"
to = "https://thetawave-assets.s3.amazonaws.com/free_assets/backgrounds/:splat"

[[redirects]]
from = "/assets/planets/*"
to = "https://thetawave-assets.s3.amazonaws.com/free_assets/planets/:splat"
