[[redirects]]
from = "/assets/backgrounds/*"
to = "https://assets.thetawave.metalmancy.tech/free_assets/backgrounds/:splat"

[[redirects]]
from = "/assets/planets/*"
to = "https://assets.thetawave.metalmancy.tech/free_assets/planets/:splat"
